# fish completion for aless, written by `aless --generate complete-fish`.
# Install it as aless.fish in a directory on $fish_complete_path.
complete -c aless -l json -d 'the document as JSON (the default)'
complete -c aless -l paths -d 'an entry for the start and each node below'
complete -c aless -l find -x -d 'the entries whose "key": value text matches'
complete -c aless -l where -d 'the start\'s entry: its path and position'
complete -c aless -l check -d 'parse each FILE and report on each'
complete -c aless -l render -x -a 'css csv expr feed ini json json5 jsonc jsonic jsonl markdown pgn proto semver toml xml yaml zon' -d 'the value written as FORMAT, streamed'
complete -c aless -l alchemy -r -F -d 'run the alchemy program in FILE'
complete -c aless -l alchemy-expr -x -d 'the same, the program on the command line'
complete -c aless -l explain -d 'the program\'s plan as JSON, and no run'
complete -c aless -l path -x -d 'start at PATH, in jq syntax'
complete -c aless -l at -x -d 'start at the node at a source position'
complete -c aless -l limit -x -d 'at most N entries (default 200; 0 for all)'
complete -c aless -l compact -d 'JSON on one line, an error\'s too'
complete -c aless -l max-output -x -d 'cap a program\'s output (default 1G)'
complete -c aless -s k -l kind -l format -x -a 'json jsonl jsonic jsonc json5 yaml toml ini csv tsv xml zon markdown feed css proto pgn expr semver text' -d 'parse every input as FORMAT'
complete -c aless -l grammar -r -F -d 'a format of your own, from an ABNF grammar'
complete -c aless -l grammar-expr -x -d 'the same, the grammar on the command line'
complete -c aless -l depth -x -d 'list N levels down; the viewer folds deeper'
complete -c aless -l indent -x -d 'indentation per level (default 2)'
complete -c aless -l key -x -d 'member a root is written under (items)'
complete -c aless -l max-size -x -d 'refuse an input over SIZE (default 64M)'
complete -c aless -l timeout -x -d 'stop a parse past SECONDS (default none)'
complete -c aless -l no-watch -d 'do not reload files when they change'
complete -c aless -l watch -d 'reload files when they change (the default)'
complete -c aless -s m -l mode -x -a 'data line' -d 'start in data (default) or line mode'
complete -c aless -s n -l line-numbers -d 'show absolute line numbers'
complete -c aless -s N -l no-line-numbers -d 'hide absolute line numbers'
complete -c aless -s r -l relative-line-numbers -d 'show relative line numbers'
complete -c aless -s R -l no-relative-line-numbers -d 'hide relative line numbers'
complete -c aless -l scrolloff -x -d 'rows kept around the focus (default 3)'
complete -c aless -l hidden -d 'show dot-files in the explorer'
complete -c aless -l ascii -d 'draw fold markers in ASCII'
complete -c aless -l no-color -l no-colour -d 'no colours (as NO_COLOR does)'
complete -c aless -l no-mouse -d 'do not capture the mouse'
complete -c aless -l panes -x -a 'out program out,program' -d 'open the output and program panes'
complete -c aless -l stacked -d 'stack the panes'
complete -c aless -s h -l help -d 'the options (-h), or the whole reference'
complete -c aless -s V -l version -d 'the version'
complete -c aless -l generate -x -a 'man complete-bash complete-zsh complete-fish complete-powershell skill' -d 'a man page, shell completions or the skill'
